# - Find libsqlite library and headers
# The module defines the following variables:
#
# SQLITE_FOUND
# SQLITE_INCLUDE_DIRS
# SQLITE_LIBRARIES
# SQLITE_VERSION

# Copyright (c) 2013 Tristan Le Guern <leguern AT medu.se>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

# Check if the definitions are not already in cache
IF(SQLITE_INCLUDE_DIRS AND SQLITE_LIBRARIES)
    SET(SQLITE_FIND_QUIETLY TRUE)
ENDIF(SQLITE_INCLUDE_DIRS AND SQLITE_LIBRARIES)

FIND_PACKAGE(PkgConfig QUIET)
PKG_CHECK_MODULES(PC_SQLITE sqlite3)
SET(SQLITE_VERSION ${PC_SQLITE_VERSION})
SET(SQLITE_DEFINITIONS ${PC_SQLITE_DEFINITIONS})

FIND_PATH(SQLITE_INCLUDE_DIR sqlite3.h
    HINTS ${PC_SQLITE_INCLUDE_DIRS}
)

FIND_LIBRARY(SQLITE_LIBRARY NAMES sqlite3 libsqlite3
    HINTS ${PC_SQLITE_LIBRARY_DIRS}
)

# cmake GUI niceness
MARK_AS_ADVANCED(SQLITE_INCLUDE_DIR SQLITE_LIBRARY)

if(SQLITE_INCLUDE_DIR AND SQLITE_LIBRARY AND SQLITE_VERSION)
    set(SQLITE_FOUND TRUE)
endif()

IF(SQLITE_FOUND)
    SET(SQLITE_LIBRARIES ${SQLITE_LIBRARY})
    SET(SQLITE_INCLUDE_DIRS ${SQLITE_INCLUDE_DIR})
ENDIF(SQLITE_FOUND)

