# - Find libldap library and headers
# The module defines the following variables:
#
# CONFUSE_FOUND
# CONFUSE_INCLUDE_DIRS
# CONFUSE_LIBRARIES
# CONFUSE_VERSION

# Copyright (c) 2013 Tristan Le Guern <leguern AT medu.se>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

# Check if the definitions are not already in cache
IF(CONFUSE_INCLUDE_DIRS AND CONFUSE_LIBRARIES)
    SET(CONFUSE_FIND_QUIETLY TRUE)
ENDIF(CONFUSE_INCLUDE_DIRS AND CONFUSE_LIBRARIES)

FIND_PACKAGE(PkgConfig QUIET)
PKG_CHECK_MODULES(PC_CONFUSE libconfuse)
SET(CONFUSE_VERSION ${PC_CONFUSE_VERSION})
SET(CONFUSE_DEFINITIONS ${PC_CONFUSE_DEFINITIONS})

FIND_PATH(CONFUSE_INCLUDE_DIR confuse.h
    HINTS ${PC_CONFUSE_INCLUDE_DIRS}
)

FIND_LIBRARY(CONFUSE_LIBRARY NAMES confuse libconfuse
    HINTS ${PC_CONFUSE_LIBRARY_DIRS}
)

# cmake GUI niceness
MARK_AS_ADVANCED(CONFUSE_INCLUDE_DIR CONFUSE_LIBRARY)

if(CONFUSE_INCLUDE_DIR AND CONFUSE_LIBRARY AND CONFUSE_VERSION)
    set(CONFUSE_FOUND TRUE)
endif()

IF(CONFUSE_FOUND)
    SET(CONFUSE_LIBRARIES ${CONFUSE_LIBRARY})
    SET(CONFUSE_INCLUDE_DIRS ${CONFUSE_INCLUDE_DIR})
ENDIF(CONFUSE_FOUND)

