# - Find libldap library and headers
# The module defines the following variables:
#
# LDAP_FOUND
# LDAP_INCLUDE_DIRS
# LDAP_LIBRARIES
# LDAP_VERSION

# Copyright (c) 2013 Tristan Le Guern <leguern AT medu.se>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

# Check if the definitions are not already in cache
IF(LDAP_INCLUDE_DIRS AND LDAP_LIBRARIES)
    SET(LDAP_FIND_QUIETLY TRUE)
ENDIF(LDAP_INCLUDE_DIRS AND LDAP_LIBRARIES)

FIND_PACKAGE(PkgConfig QUIET)
PKG_CHECK_MODULES(PC_LDAP ldap)
SET(LDAP_VERSION ${PC_LDAP_VERSION})
SET(LDAP_DEFINITIONS ${PC_LDAP_DEFINITIONS})

FIND_PATH(LDAP_INCLUDE_DIR ldap.h
    HINTS ${PC_LDAP_INCLUDE_DIRS}
)

FIND_LIBRARY(LDAP_LIBRARY NAMES ldap libldap
    HINTS ${PC_LDAP_LIBRARY_DIRS}
)

# cmake GUI niceness
MARK_AS_ADVANCED(LDAP_INCLUDE_DIR LDAP_LIBRARY)

if(LDAP_INCLUDE_DIR AND LDAP_LIBRARY AND LDAP_VERSION)
    set(LDAP_FOUND TRUE)
endif()

IF(LDAP_FOUND)
    SET(LDAP_LIBRARIES ${LDAP_LIBRARY})
    SET(LDAP_INCLUDE_DIRS ${LDAP_INCLUDE_DIR})
ENDIF(LDAP_FOUND)

